version: '3.8'
services:
  mongodb_container:
    image: mongo:latest
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - /C/Users/victo/Docker/MongoDB/database/:/data/db

#  app1_container:
#    image: demo-project:0.0.1-SNAPSHOT
#    hostname: app
#    ports:
#      - 8080:8080
#    volumes:
#      - app1_data_container:/data/logs
#    restart: on-failure
#    depends_on:
#      - mongodb_container
#    links:
#      - mongodb_container
#    environment:
#      WAIT_HOSTS: mongo:27017
#volumes:
#  mongodb_data_container: /C/Users/victo/Docker/MongoDB/database/
#  app1_data_container:
